# Generated by Django 6.0.4 on 2026-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_age_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='In Use', max_length=20),
        ),
    ]
