# Generated by Django 6.0.4 on 2026-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='complications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='creatinine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='fluid_removed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='heparin_dose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='medications_given',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='post_bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='post_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='urea',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
