# Generated by Django 6.0.4 on 2026-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_treatmentsession_complications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='creatinine',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='urea',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pre_creatinine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pre_potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pre_sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pre_urea',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
