# Generated by Django 6.0.4 on 2026-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_treatmentsession_creatinine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pre_creatinine',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pre_potassium',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pre_sodium',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pre_urea',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_alerts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='vascular_access',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
