# Generated by Django 6.0.4 on 2026-04-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_appointment_pre_creatinine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentsession',
            name='outcome',
            field=models.CharField(choices=[('Optimal', 'Optimal'), ('Stable', 'Stable'), ('BP Dip Observed', 'Hypotension (BP Dip)'), ('Cramps Observed', 'Muscle Cramps'), ('Nausea/Vomiting', 'Nausea / Vomiting'), ('Bleeding', 'Excessive Bleeding'), ('Critical', 'Critical Complication')], default='Optimal', max_length=50),
        ),
    ]
