# Generated by Django 6.0.4 on 2026-05-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_patient_av_fistula_created_on_patient_ckd_stage_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attending_staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
