# Generated by Django 6.0.4 on 2026-05-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment_attending_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='attending_staff',
        ),
        migrations.AddField(
            model_name='patient',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='aadhar_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/aadhar/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cmchis_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cmchis_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/cmchis/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ration_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/ration/'),
        ),
    ]
