# Generated by Django 6.0.4 on 2026-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_appointment_attending_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sgot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sgpt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='electrolytes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
