# Generated by Django 6.0.4 on 2026-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patient_sgot_patient_sgpt_alter_patient_electrolytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
