# Generated by Django 6.0.4 on 2026-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_patient_status_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard Unit'), ('HIV', 'HIV-Dedicated Unit'), ('HCV', 'HCV-Dedicated Unit'), ('HIV_HCV', 'HIV & HCV-Dedicated Unit')], default='Standard', max_length=20),
        ),
    ]
