# Generated by Django 6.0.4 on 2026-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
    ]
