# Generated by Django 6.0.4 on 2026-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_servicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='unit_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
