# Generated by Django 6.0.4 on 2026-05-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_machine_unit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Dialyzers', 'Dialyzers'), ('Tubing', 'Tubing'), ('Medication', 'Medication'), ('PPE', 'PPE'), ('Consumables', 'Consumables')], default='Consumables', max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('sets', 'sets'), ('vials', 'vials'), ('boxes', 'boxes'), ('bags', 'bags')], default='pcs', max_length=10)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='attending_staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('Self-Pay', 'Self-Pay'), ('CMCHIS', 'CMCHIS'), ('Insurance', 'Insurance')], default='Self-Pay', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.patient')),
            ],
        ),
    ]
