# Generated by Django 6.0.4 on 2026-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inventoryitem_appointment_attending_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='amc_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='amc_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='donated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='has_bpm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='running_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='warranty_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
