# Generated by Django 6.0.4 on 2026-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_staff_age_staff_edu_10th_mark_staff_edu_10th_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='staff/documents/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification_proof',
            field=models.FileField(blank=True, null=True, upload_to='staff/documents/'),
        ),
    ]
