# Generated by Django 6.0.4 on 2026-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_staff_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Dialyzers', 'Dialyzers'), ('Tubing', 'Tubing'), ('Medication', 'Medication'), ('PPE', 'PPE'), ('Consumables', 'Consumables'), ('Others', 'Others')], default='Consumables', max_length=50),
        ),
    ]
