# Generated by Django 6.0.4 on 2026-05-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_inventoryitem_other_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='api.treatmentsession')),
            ],
        ),
    ]
