# Generated by Django 6.0.4 on 2026-05-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sessionconsumable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half-Day', 'Half-Day'), ('Leave', 'On Leave')], default='Present', max_length=20)),
                ('work_hours', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.staff')),
            ],
            options={
                'ordering': ['-date', 'staff__name'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
